// ═══════════════════════════════════════════════════════════════
//  POSTS INDEX — Shahnaz Kulsoom Blog
//
//  HOW TO ADD A NEW POST:
//  1. Open composer.html → write your post → click "Export Post File"
//  2. Save the downloaded  posts/your-slug.js  into the posts/ folder
//  3. Add one metadata entry here in POSTS_INDEX (no body needed)
//  4. Done — blog updates automatically on next page load.
//
//  Body content lives in posts/<slug>.js — loaded on demand.
//  This file stays tiny no matter how many posts you publish.
// ═══════════════════════════════════════════════════════════════

const POSTS_INDEX = [
  {
    slug:     "why-i-switched-to-dotnet-8",
    title:    "Why I Switched from .NET 6 to .NET 8 and Never Looked Back",
    category: ".NET",
    date:     "May 2026",
    readTime: "5 min read",
    excerpt:  "A practical walkthrough of the performance gains, new APIs, and developer experience improvements that made .NET 8 a game-changer for our enterprise projects.",
    subtitle: "Real numbers, real projects — here's what actually changed when we migrated."
  },
  {
    slug:     "redis-caching-strategies",
    title:    "Redis Caching Strategies That Cut Our API Response Time by 60%",
    category: "Azure",
    date:     "April 2026",
    readTime: "7 min read",
    excerpt:  "Real-world patterns for using Redis in .NET microservices — from cache-aside to pub/sub, with code examples from production systems.",
    subtitle: "Practical patterns we use in production — not textbook theory."
  }
  // ← paste new post metadata here (generated by composer.html)
];
